### ISSUE TITLE
SCR: questions regarding RTMI listing in "Create SCR"

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3S-DEVELOPMENT#220]
Question 1: when creating SCR, after selecting the old customer, it lists the RTMI for that customer.  How many RTMI can be listed in one page?

Question 2: If there are multiple pages of RTMI listed for that SCR, and the user want to select some (not all) RTMI from each page, after clicking the checkbox in one page and go to the next page, will the check marks stay?  Or will they be removed when going to the next page?

Question 3: what RTMI are shown on the list?  All RTMI with the "old customer" with status "OutInspectApprove"?  Does it include both Rental and Leasing?

Thanks

**Comment by d3sqa** [comment]
Answer 1: By default, 25 RTMI records are displayed at the grid. The number of records displayed in the grid can also be changed to 50 or 500

Answer 2: No, the checks will not remain in place whenever the page is changed. This is due to the server side pagination we have implemented. Only the RTMIs selected per page will remain in place unless the page is changed

Answer 3: Yes, all RTMIs [Rental and Leasing] having OUTINSPECTAPPROVED status will be displayed in the list

**Comment by gchan-trailcon** [comment]
Reply to answer 2: In create SCR, how can a user select some RTMI from each page? As the check marks won't stay when you go to next page.  Does it mean we have to list all the RTMI in one page?  If so, We will have to change the list to 500.

**Comment by d3sqa** [comment]
Elaboration to Answer 2: There is an option in the drop down for # of records per page called 'Show All'. Please use 'Show All', so that all the unit records could be displayed on the single page, then use the Check All check box to select all units at once. 

Please refer to the below attached screenshots:

![screenshot_6](https://cloud.githubusercontent.com/assets/13255706/11863396/6e22466a-a4b5-11e5-90aa-9dcf56772226.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/13255706/11863453/c70ac23e-a4b5-11e5-845d-1e7675840fc2.png)

**Comment by gchan-trailcon** [comment]
Checked, changing the number of displayed item per page is a valid work-around for the issue.

Is it possible to fix the multi page selection issue in the next version?

**Comment by giovanicani** [comment]
Just adding my 2 cents here... do we need pagination ? Removing pagination just make things easier... I don't thing we will ever have more than 500 units in one SCR, and if we ever do, we could split into 2 on the system.

**Comment by d3sqa** [comment]
As per the suggestion of @giovanicani, we have removed the pagination from Unit # grid while creating the SCR. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
checked.
